import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Providers from './providers';
import Header from '../components/layout/header';
import { Topbar } from '../components/layout/topbar';
import { Linksbar } from '../components/layout/linksbar';
import { Toaster } from 'components/ui/toaster';

import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
	title: 'Biovac | Your healthy choice',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`text-black ${inter.className}`}>
				<Providers>
					<Topbar />
					<Header />
					<Linksbar />
					<main className="container py-6">{children}</main>
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
