import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from './components/header';
import { Topbar } from './components/topbar';
import { Linksbar } from './components/linksbar';

const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800'] });

export const metadata: Metadata = {
    title: 'Biovac | Your healthy choice',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Topbar />
                <Header />
                <Linksbar />
                <div className="container">{children}</div>
            </body>
        </html>
    );
}
